### ISSUE TITLE
-executeMethod parameters are being parsed incorrectly

### ISSUE THREAD

**Issue by Chris1990** [guitarrapc/UnityBuildRunner#37]
Hey Guys, I have come across a issue with command line arguments.

Example Command:
`UnityBuildRunner -u ".\Unity.exe" -projectPath "C:\Sandbox\GitSandbox\AmazeBalls\" -batchmode -quit -nographics -executeMethod JenkinsBuilder.Build "AmazeBalls" "5.5" "C:\Sandbox\GitSandbox\AmazeBalls\My Builds\Builds\"`

As you can see, I overdid it with quotation marks because I have been trying to work out the issue. Now if I output my args I get the following:
_.\Unity.exe
-projectPath
C:\Sandbox\GitSandbox\AmazeBalls
-batchmode
-quit
-nographics
-executeMethod
JenkinsBuilder.Build
AmazeBalls
5.5
**C:\Sandbox\GitSandbox\AmazeBalls\My"
Builds\Builds"**
-logFile
unitybuild.log_

As you can see, it seems to be ignoring my quotes. The reason why I am pointing it in your direction is because if I run my build straight to unity my args are correct, example:
`Unity.exe -projectPath "C:\Sandbox\GitSandbox\AmazeBalls\" -batchmode -quit -nographics -executeMethod JenkinsBuilder.Build "AmazeBalls" "5.5" "C:\Sandbox\GitSandbox\AmazeBalls\My Builds\Builds\"`

I got no output for you, but I can see my build is placed in the correct location.

**Comment by ChrisMcCaffertyOI** [comment]
I ended up cloning your repo and writing some unit tests with my arguments and worked out my issue. 

-projectPath "C:\Sandbox\GitSandbox\AmazeBalls\"

That last slash caused havoc. Should be:
-projectPath "C:\Sandbox\GitSandbox\AmazeBalls"

Meh, what can you do. You can close this issue.
